// Auto-generated by ArtHound estimation engine setup wizard.
// Key format: "VAR1|VAR2|VAR3" where values match field values in the Assets table.
// Variable order: Item Type | Priority | Team (from Product)
//
// To regenerate, re-run the ⚙ setup wizard in the app.

module.exports = {
  _variableFields: ["Item Type","Priority","Team (from Product)"],

  'Axe|2|Live Content': 'Axe_2_LiveContent',
  'Axe|2|Maps': 'Axe_2_Maps',
  'Axe|3|Characters': 'Axe_3_Characters',
};