// Auto-generated by ArtHound estimation engine setup wizard.
// Key format: "VAR1|VAR2|VAR3" where values match field values in the Assets table.
// Variable order: Item Type | Team (from Product) | Priority
//
// To regenerate, re-run the ⚙ setup wizard in the app.

module.exports = {
  _variableFields: ["Item Type","Team (from Product)","Priority"],

  'Axe|Characters|2': 'Axe_Characters_2',
  'Mace|Live Content|2': 'Mace_LiveContent_2',
  'Character ability|Characters|2': 'Characterability_Characters_2',
  'Small Prop|Maps|4': 'SmallProp_Maps_4',
  'Character Skin|Live Content|5': 'CharacterSkin_LiveContent_5',
  'Point of Interest|Maps|4': 'PointofInterest_Maps_4',
};