// Auto-generated by ArtHound estimation engine setup wizard.
// Key format: "VAR1|VAR2|VAR3" where values match field values in the Assets table.
// Variable order: Item Type | Priority | Team (from Product)
//
// To regenerate, re-run the ⚙ setup wizard in the app.

module.exports = {
  _variableFields: ["Item Type","Team (from Product)","Priority"],
};