-- 007_generated_tasks.sql
-- Run after 006_sync_layer.sql
--
-- Stores a snapshot of every work schedule generated by ArtHound.
-- Airtable (or another source tool) remains the operational source of truth
-- for task tracking. This table is ArtHound-internal — it records what was
-- computed and dispatched, not what the studio does with it afterward.
--
-- Primary use: CuToolU bot context (NumberBot variance flags, ProcessBot wait
-- analysis, future forecasting). Bots read here rather than hitting source tools.
--
-- canonical_asset_id links each task to the ArtHound-global asset identity,
-- so records survive source-tool migrations (Airtable → ShotGrid etc.).
-- source_record_id is the created task record ID in the source tool — stored
-- for potential future write-back or dedup, not for identity.

create table generated_tasks (
  id                  uuid primary key default gen_random_uuid(),

  -- ArtHound identity: canonical asset this task belongs to
  canonical_asset_id  uuid not null references canonical_assets(id),
  studio_id           uuid not null references studios(id),

  -- Where the task was written after generation
  source_type         text not null default 'airtable'
                        check (source_type in ('airtable', 'jira', 'shotgrid', 'arthound')),
  source_record_id    text,  -- e.g. Airtable recXXX of the created task; null until confirmed

  -- Task fields (snapshot at time of generation)
  task_name           text not null,
  workflow_step_id    uuid references workflow_steps(id),  -- null if step not yet mapped
  craft               text,
  estimate_days       numeric(10,2),
  variable_values     jsonb not null default '{}',  -- the combination that produced this estimate
  start_date          date,
  end_date            date,

  generated_at        timestamptz default now()
);

create index on generated_tasks (canonical_asset_id);
create index on generated_tasks (studio_id);
create index on generated_tasks (studio_id, canonical_asset_id);
create index on generated_tasks (generated_at desc);


-- ── Row Level Security ────────────────────────────────────────────────────────
-- Studio-scoped only. Vendors never see generated tasks unless explicitly
-- dispatched through the payload system.

alter table generated_tasks enable row level security;

create policy "gt_studio" on generated_tasks for all using (
  studio_id in (select studio_id from studio_members where user_id = auth.uid())
);
